[[collection]]
type="box"
img="https://avatars.githubusercontent.com/u/14349453?v=4"
link="https://ihexon.github.io/"
rotate=true
title="ihexon"
subtitle="æµ·è‹”å‘³çš„å”‡ğŸ‘„"

[[collection]]
type="box"
img="https://avatars.githubusercontent.com/u/125887503?v=4"
link="https://dilutepillow.github.io/"
rotate=true
title="æ°´æ°”æ è¿‡"
subtitle="æ™šé¥­åï¼Œä¸€èµ·æ•£æ­¥å§ã€‚"

[[collection]]
type="box"
img="https://raw.githubusercontent.com/manesec/manesec/refs/heads/main/avatar.png"
link="https://manesec.github.io/"
rotate=true
title="Manesec"
subtitle="å“ªè£éƒ½æ˜¯çŸ¥è­˜ç›²å€ QAQ"

[[collection]]
type="box"
img="https://flowerwitch.github.io/images/avatar.jpg"
link="https://flowerwitch.github.io/"
rotate=true
title="Flower"
subtitle="Hi Im Flower"
